/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemenkaryawan;

import java.awt.event.ActionEvent;


/**
 *
 * @author farsa
 */
public class CRUDKaryawanFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CRUDKaryawanFrame.class.getName());
    private Karyawan karyawanLogin;
    /**
     * Creates new form CRUDKaryawanFrame
     */
    
    private String namaAktif = "";

    public CRUDKaryawanFrame(Karyawan karyawanLogin) {
        this.karyawanLogin = karyawanLogin;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);    
        setupTabel();    
        loadDataTabel();

        // TAMBAHAN 2: Kalau klik tombol X → buka MainFrameGUI
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                new MainFrameGUI(karyawanLogin).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        lblNama = new javax.swing.JLabel();
        lblJabatan = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        lblGaji = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnKembali = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 300));

        pnlHeader.setBackground(new java.awt.Color(0, 102, 255));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("KELOLA DATA KARYAWAN");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKaryawan);

        lblNama.setText("Nama        :");

        lblJabatan.setText("Jabatan     :");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        lblNoTelp.setText("No Tlpn    :");

        lblGaji.setText("Gaji            :");

        lblPassword.setText("Password  :");

        btnTambah.setBackground(new java.awt.Color(51, 255, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText(" Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(51, 51, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText(" Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText(" Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBersihkan.setBackground(new java.awt.Color(153, 153, 153));
        btnBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBersihkan.setText(" Bersihkan");
        btnBersihkan.addActionListener(this::btnBersihkanActionPerformed);

        lblStatus.setText("      ");

        btnKembali.setBackground(new java.awt.Color(51, 51, 51));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        lblId.setText("Id               :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword))
                            .addComponent(btnBersihkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama)
                                    .addComponent(lblJabatan)
                                    .addComponent(lblNoTelp)
                                    .addComponent(lblGaji)
                                    .addComponent(lblId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtJabatan)
                                    .addComponent(txtNoTelp)
                                    .addComponent(txtGaji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtId))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJabatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoTelp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGaji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBersihkan))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String idStr    = txtId.getText().trim();
        String nama     = txtNama.getText().trim();
        String jabatan  = txtJabatan.getText().trim();
        String noTelp   = txtNoTelp.getText().trim();
        String gajiStr  = txtGaji.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        // Validasi ID kosong
        if (idStr.isEmpty()) {
            lblStatus.setText("⚠ ID tidak boleh kosong!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }
        
        // Validasi ID harus angka
        int id;
        try {
            id = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            lblStatus.setText("⚠ ID harus berupa angka!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }
        
            // Validasi field lain
        if (nama.isEmpty() || jabatan.isEmpty() ||
            noTelp.isEmpty() || gajiStr.isEmpty() || password.isEmpty()) {
            lblStatus.setText("⚠ Semua field harus diisi!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }
        
        // Validasi input kosong
        if (nama.isEmpty() || jabatan.isEmpty() || 
            noTelp.isEmpty() || gajiStr.isEmpty() || password.isEmpty()) {
            lblStatus.setText("⚠ Semua field harus diisi!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        // Validasi gaji harus angka
        double gaji;
        try {
            gaji = Double.parseDouble(gajiStr);
        } catch (NumberFormatException e) {
            lblStatus.setText("⚠ Gaji harus berupa angka!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        // Simpan ke database
        boolean ok = KaryawanDAO.tambahKaryawan(id,nama, jabatan, noTelp, gaji, password);
        if (ok) {
            lblStatus.setText("✅ Karyawan " + nama + " berhasil ditambahkan!");
            lblStatus.setForeground(new java.awt.Color(22, 163, 74));
            loadDataTabel();
            bersihkanForm();
        } else {
            lblStatus.setText("❌ Gagal menambahkan karyawan!");
            lblStatus.setForeground(java.awt.Color.RED);
        }


        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (namaAktif.isEmpty()) {
            lblStatus.setText("⚠ Pilih karyawan dari tabel dulu!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        String namaBaru = txtNama.getText().trim();
        String jabatan  = txtJabatan.getText().trim();
        String noTelp   = txtNoTelp.getText().trim();
        String gajiStr  = txtGaji.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (namaBaru.isEmpty() || jabatan.isEmpty() || 
            noTelp.isEmpty() || gajiStr.isEmpty()) {
            lblStatus.setText("⚠ Semua field harus diisi!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        double gaji;
        try {
            gaji = Double.parseDouble(gajiStr);
        } catch (NumberFormatException e) {
            lblStatus.setText("⚠ Gaji harus berupa angka!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        // Konfirmasi sebelum update
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Update data karyawan " + namaAktif + "?",
            "Konfirmasi Update",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            boolean ok = KaryawanDAO.updateKaryawan(
                namaAktif, namaBaru, jabatan, noTelp, gaji, password);
            if (ok) {
                lblStatus.setText("✅ Data berhasil diupdate!");
                lblStatus.setForeground(new java.awt.Color(22, 163, 74));
                loadDataTabel();
                bersihkanForm();
            } else {
                lblStatus.setText("❌ Gagal mengupdate data!");
                lblStatus.setForeground(java.awt.Color.RED);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (namaAktif.isEmpty()) {
            lblStatus.setText("⚠ Pilih karyawan dari tabel dulu!");
            lblStatus.setForeground(java.awt.Color.RED);
            return;
        }

        // Konfirmasi sebelum hapus
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin hapus karyawan " + namaAktif + "?\nData tidak bisa dikembalikan!",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            boolean ok = KaryawanDAO.hapusKaryawan(namaAktif);
            if (ok) {
                lblStatus.setText("✅ Karyawan " + namaAktif + " berhasil dihapus!");
                lblStatus.setForeground(new java.awt.Color(22, 163, 74));
                loadDataTabel();
                bersihkanForm();
            } else {
                lblStatus.setText("❌ Gagal menghapus karyawan!");
                lblStatus.setForeground(java.awt.Color.RED);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        bersihkanForm();
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainFrameGUI(karyawanLogin).setVisible(true); // buka MainFrameGUI
        dispose(); // tutup halaman ini
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void setupTabel() {
        // Definisikan kolom tabel
        String[] kolom = {"Nama", "Jabatan", "No Telp", "Gaji", "ID"};
        javax.swing.table.DefaultTableModel model = 
            new javax.swing.table.DefaultTableModel(kolom, 0) {
                @Override
                public boolean isCellEditable(int row, int col) {
                    return false; // tabel tidak bisa diedit langsung
                }
            };
        tblKaryawan.setModel(model);
        tblKaryawan.setRowHeight(30);
        tblKaryawan.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        // Klik baris tabel → isi form otomatis
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int row = tblKaryawan.getSelectedRow();
                if (row >= 0) {
                    namaAktif = tblKaryawan.getValueAt(row, 0).toString();
                    txtId.setText(tblKaryawan.getValueAt(row, 4).toString());
                    txtNama.setText(namaAktif);
                    txtJabatan.setText(tblKaryawan.getValueAt(row, 1).toString());
                    txtNoTelp.setText(tblKaryawan.getValueAt(row, 2).toString());
                    txtGaji.setText(tblKaryawan.getValueAt(row, 3).toString()
                        .replace("Rp", "").replace(".", "").replace(",00", "").trim());
                    txtPassword.setText("");
                    lblStatus.setText("Karyawan dipilih: " + namaAktif);
                    lblStatus.setForeground(java.awt.Color.BLUE);
                }
            }
        });
    }

    private void loadDataTabel() {
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) tblKaryawan.getModel();
        model.setRowCount(0); // kosongkan tabel dulu

        java.text.NumberFormat rupiah = java.text.NumberFormat
            .getCurrencyInstance(new java.util.Locale("id", "ID"));

        for (Karyawan k : KaryawanDAO.getAllKaryawan()) {
            model.addRow(new Object[]{
                k.getNama(),
                k.getJabatan(),
                k.getNoTelp(),
                rupiah.format(k.getGaji()),
                k.getId()
            });
        }
        lblStatus.setText("Total karyawan: " + model.getRowCount());
        lblStatus.setForeground(java.awt.Color.DARK_GRAY);
    }
    
    private void bersihkanForm() {
        namaAktif = "";
        txtId.setText("");
        txtNama.setText("");
        txtJabatan.setText("");
        txtNoTelp.setText("");
        txtGaji.setText("");
        txtPassword.setText("");
        tblKaryawan.clearSelection();
        lblStatus.setText(" ");
    }
}
